version: '3'

services:
  challenger-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenger
    ports:
      - '5434:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
